# Generated by Django 4.0 on 2022-11-30 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('in_process', 'EN COURS'), ('ended', 'TERMINER'), ('cancelled', 'ANUULER')], default='in_process', max_length=100)),
                ('make_at', models.DateTimeField(auto_now_add=True)),
                ('is_over', models.BooleanField(default=False)),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'db_table': 'campagne',
            },
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uid', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField()),
                ('telephone', models.CharField(max_length=100)),
                ('is_send', models.BooleanField(default=False)),
                ('operateur', models.CharField(default='OM', max_length=10)),
                ('type', models.CharField(choices=[('20%', '20% pour 6 mois'), ('30%', '30% pour 12 mois'), ('10%', 'credite mon compte subito')], default='20%', max_length=100, null=True)),
                ('remboursement', models.CharField(choices=[('20%', 'transfert'), ('payment', 'payment'), ('credit', 'credit'), ('forfait', 'forfait')], default='20%', max_length=100, null=True)),
                ('status', models.CharField(choices=[('in_process', 'EN COURS'), ('validate', 'VALIDER'), ('cancelled', 'ANUULER')], default='in_process', max_length=100)),
                ('make_at', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campagne')),
                ('investisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.investisseur')),
            ],
            options={
                'verbose_name': 'Investissement',
                'verbose_name_plural': 'Investissements',
                'db_table': 'investissement',
            },
        ),
    ]
