# Generated by Django 4.0 on 2022-12-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='status',
            field=models.CharField(choices=[('in_process', 'EN COURS'), ('ended', 'TERMINER'), ('cancelled', 'ANNULER')], default='in_process', max_length=100),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='remboursement',
            field=models.CharField(choices=[('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel'), ('Aterme', 'A terme')], default='Trimestriel', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='status',
            field=models.CharField(choices=[('in_process', 'EN COURS'), ('validate', 'VALIDER'), ('cancelled', 'ANNULER')], default='in_process', max_length=100),
        ),
    ]
