# Generated by Django 4.0 on 2022-12-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_campagne_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investissement',
            name='remboursement',
            field=models.CharField(choices=[('Trimestriel', 'Trimestriel'), ('Semestriel', 'Semestriel'), ('Aterme', 'A terme(Annuel)')], default='Trimestriel', max_length=100, null=True),
        ),
    ]
