# Generated by Django 4.0 on 2022-12-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_investissement_remboursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='amount_needed',
            field=models.IntegerField(null=True),
        ),
    ]
