# Generated by Django 4.0 on 2022-12-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_campagne_debut_campagne_campagne_fin_campagne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echeance',
            name='investissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investissement'),
        ),
    ]
