# Generated by Django 4.0 on 2022-11-30 12:49

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=65, unique=True, verbose_name='email')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='dernier connexion')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
            managers=[
                ('objects', accounts.models.MyAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Investisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('indicatif', models.CharField(blank=True, max_length=4, null=True)),
                ('civilite', models.CharField(blank=True, choices=[('Mr', 'Monsieur'), ('Mme', 'Madame'), ('Inconnue', 'Inconnue')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
            options={
                'verbose_name': 'Investisseur',
                'verbose_name_plural': 'Investisseurs',
                'db_table': 'investisseur',
            },
        ),
    ]
