# Generated by Django 4.0 on 2022-12-01 13:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=accounts.models.get_default_profile_image, max_length=255, null=True, upload_to=accounts.models.get_profile_image_filepath),
        ),
        migrations.AddField(
            model_name='investisseur',
            name='carte',
            field=models.ImageField(blank=True, default=accounts.models.get_default_investisseur_carte, max_length=255, null=True, upload_to=accounts.models.get_investisseur_carte),
        ),
        migrations.AddField(
            model_name='investisseur',
            name='cni',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
