# Generated by Django 4.0 on 2022-12-10 21:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_profile_image_investisseur_carte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=accounts.models.get_profile_image_filepath),
        ),
        migrations.AlterField(
            model_name='investisseur',
            name='carte',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=accounts.models.get_investisseur_carte),
        ),
    ]
